[project]
name = "piqtree-demo"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.15"
dependencies = [
    "piqtree[extra]>=0.6.1",
    "sc-supertree>=2025.12.9",
    "cogent3>=2025.12.10a3",
]

[dependency-groups]
dev = ["ruff>=0.14.4"]
