[project]
name = "piqtree-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["piqtree[extra]>=0.6.1", "sc-supertree>=2025.12.9"]

[dependency-groups]
dev = ["ruff>=0.14.4"]
